version: "2.1"

services:
  sonos:
    build: node-sonos-http-api
    ports:
      - "5005:5005"
    network_mode: bridge

  prayer:
    build: prayer-time-service
    ports:
      - "3000:3000"
    network_mode: bridge

networks:
  default:
    external:
      name: bridge
