version: '2'

services:
  sonos:
    build: node-sonos-http-api
    ports:
      - "5005:5005"
    network_mode: "host"

  prayer:
    build: prayer-time-service
    ports:
      - "3000:3000"
    links:
      - sonos
